version: '3'
services:
  java-srv:
    build:
      context: java-srv
    command: /bin/sh -c "/wait && gradle run"
    environment:
      - WAIT_HOSTS=db:26257
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - db
    links:
      - "db:db"

  db:
    image: cockroachdb/cockroach:v19.2.4
    container_name: db
    ports:
     - "20000:26257"
     - "8000:8080"
    command: start --insecure

  db_1:
    image: cockroachdb/cockroach:v19.2.4
    container_name: db_1
    ports:
     - "20001:26257"
     - "8001:8080"
    command: start --insecure --join=db

  db_2:
    image: cockroachdb/cockroach:v19.2.4
    container_name: db_2
    ports:
     - "20002:26257"
     - "8002:8080"
    command: start --insecure --join=db

